data = {
    "taunts" : [
        "Is this the tutorial? You're making it too easy!",
        "I've seen bots play better than this. Seriously.",
        "Are you lagging or just that slow? I can't tell!",
        "I haven't even used my main hand yet! Still winning!",
        "Nice try, but I'm just on a completely different level.",
        "You might want to read a guide after this match, buddy.",
        "I'm just warming up, and you're already finished?",
        "Was that an outplay or a mistake? It looked like a fail to me.",
        "I'm literally playing with one eye closed right now!",
        "Is it my birthday? Thanks for all the free gold!",
        "You're not even a challenge yet. Try harder!",
        "Wait, was that your ultimate? I didn't even notice!",
        "I'm just getting started, don't give up so soon!",
        "Should I go AFK for 5 minutes to make it fair for you?",
        "Your skillshots are missing by a mile! Aim better!",
        "I'm the main character here, you're just a cannon minion.",
        "Keep trying! Maybe you'll actually hit me next time!",
        "I'm not even trying and I'm still carrying this game.",
        "You're just another highlight in my next montage!",
        "Are you even playing or is your cat on the keyboard?"
        ],
    "morale_boosters" : [
        "Don't give up, we have the better late game scaling!",
        "Keep your heads up, we're just getting started!",
        "One good teamfight and we've got this in the bag!",
        "We’re doing great team, just stay focused and win!",
        "I believe in us! Let’s show them a real comeback!",
        "Great job everyone, let's keep this momentum going!",
        "We’re stronger together, let’s group up and crush them!",
        "Don't tilt, we are still in this 100%!",
        "Nice try team, we'll get them on the next engage!",
        "I haven’t even used my full power yet, we’ve definitely got this!",
        "Stay positive! Victory is still within our reach!",
        "We are the better team, let’s just play it smart and win!",
        "Focus on the objectives, we can still turn this around easily!",
        "Amazing effort everyone, let’s push together for the win!",
        "It’s not over until the Nexus falls! Let's goooo!",
        "I'm hyped! Let's pull off the ultimate comeback right now!",
        "Solid play team, let's keep the pressure on them!",
        "We’ve got the skills, let’s just coordinate and finish it!",
        "Everything is under control, just stay calm and follow the plan!",
        "You guys are legends! Let's win this together!"
    ],
    "Things are starting to get interesting":[
        "Impossible! How could this be?!",
        "You got lucky that time... don't get used to it!",
        "You caught me off guard... a once-in-a-lifetime miracle!",
        "A glitch in the matrix? That was impossible!",
        "Okay, you got me once, but I haven't even peaked yet!",
        "Heh... not bad. You actually made me focus for a second!",
        "Heh... it seems I've finally found a worthy opponent on this rift!",
        "Heh, you're making me sit up in my chair now. Things are getting serious!"
    ]
}